### ISSUE TITLE
Comparing Out put to a program

### ISSUE THREAD

**Issue by davidbuckleyni** [Suchiman/Runny#3]
Do you think it would be possible to compare what the output should be for the program as to what comes out I know I could store the expected results in a table and compare the output but was wanting a more elegant way of doing it? Like how codility works

**Comment by Suchiman** [comment]
Of course, in my sample i'm using [Console.SetOut](https://github.com/Suchiman/Runny/blob/0528b4aa6acab8c293acdfb8f67e105481d54fa2/Runny/Pages/Index.razor.cs#L55-L56) to redirect the output to a StringWriter and then split the string by lines or use a custom TextWriter. Then compare what has been outputted with what should have been outputted, the easiest way is just `StringWriter.ToString() == ExpectedOutput`.
